### PR TITLE
fix: Add tolerance to simple strategy

### LINKED ISSUE #26: Make E2E Rebalancer tests run faster
This could be achieved by parallelising some async operations

### LINKED ISSUE #27: Add tolerance to determine if a chain is balanced or not
For example, If a chain has 100 usdc, another 101, and another 99, we could consider them balanced by having a tolerance of 1 usdc

### LINKED ISSUE #28: Add helpers to create and restore snapshots on e2e tests
This can help handle chain state when trying different test branches

For example, I would like to reset the chain when trying to test results of different balances instead of using an aggregate state of previous tests

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #26 
Closes #27 
Closes #28 

- Parallelize some tasks so rebalancer tests build up faster
- Adds a tolerance to the simple strat so chains that are close to the balance target don't need to be rebalanced
- Adds helper functions to create and restore snapshots

### CODE REVIEW

File: typescript/cli/src/rebalancer/strategy/Strategy.ts [hunk 1]
```diff
@@ -16,14 +21,21 @@ export class Strategy implements IStrategy {
     const total = entries.reduce((sum, [, balance]) => sum + balance, 0n);
     // Get the average balance
     const target = total / BigInt(entries.length);
+
+    // Skip rebalancing when the average balance is very small
+    if (target < this.tolerance) {
+      return [];
+    }
```
Comment (fernandomg) [inline typescript/cli/src/rebalancer/strategy/Strategy.ts:28]: I'm not understanding the use of this condition. Why would you add a tolerance bigger than the average balance?

Shouldn't this throw if that condition is met? Like warning the user that's configuring something odd.

File: typescript/cli/src/commands/warp.ts [hunk 2]
```diff
@@ -438,7 +450,7 @@ export const rebalancer: CommandModuleWithContext<{
     );
 
     // Instantiates the strategy that will get rebalancing routes based on monitor results
-    const strategy: IStrategy = new Strategy();
+    const strategy: IStrategy = new Strategy(BigInt(strategyTolerance));
```
Comment (fernandomg) [inline typescript/cli/src/commands/warp.ts:454]: shall we let the user know that they should express the tolerance in integer and in "wei" (or whatever the amount of decimals that the tokens have)?

Or this is too obvious to be explained?

**Review by fernandomg — CHANGES_REQUESTED** [review]
after running this locally it went well the first run, tried a second time and got the following output:

image

File: typescript/cli/src/rebalancer/strategy/Strategy.ts (hunk 1 above)
Comment (fzavalia) [reply typescript/cli/src/rebalancer/strategy/Strategy.ts:28]: It might happen when all collaterals from the route have a really low balance, resulting in a target that is below the tolerance

File: typescript/cli/src/commands/warp.ts (hunk 2 above)
Comment (fzavalia) [reply typescript/cli/src/commands/warp.ts:454]: Added it to the command description https://github.com/BootNodeDev/hyperlane-monorepo/pull/29/commits/45d956d1974c2ef6b44d50a265cee819f608066b

**Comment by fzavalia** [comment]
> after running this locally it went well the first run, tried a second time and got the following output:
> 
> image

Try again now with this potential fix 93c0eb2c3

File: typescript/cli/src/rebalancer/strategy/Strategy.ts (hunk 1 above)
Comment (fernandomg) [reply typescript/cli/src/rebalancer/strategy/Strategy.ts:28]: can we have a test for this case?

File: typescript/cli/src/commands/warp.ts (hunk 2 above)
Comment (fernandomg) [reply typescript/cli/src/commands/warp.ts:454]: perfect!

**Review by fernandomg — APPROVED** [review]
👏

File: typescript/cli/src/rebalancer/strategy/Strategy.ts (hunk 1 above)
Comment (fzavalia) [reply typescript/cli/src/rebalancer/strategy/Strategy.ts:28]: https://github.com/BootNodeDev/hyperlane-monorepo/pull/30 🥲
