### PR TITLE
fix: Simple monitoring on rebalancer

### LINKED ISSUE #13: Implement a simple monitoring of collateral balances in the rebalancer
Should just query collateral balances of a warp route and display them. Use `typescript/infra/scripts/warp-routes/monitor/monitor-warp-route-balances.ts` as reference.

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #13 

Like the original monitor, rebalancer accepts the warp route and frequency to query for collateral.
```bash
yarn workspace @hyperlane-xyz/cli hyperlane warp rebalancer \
    --warpRouteId TKN/anvil1-anvil2-anvil3 \
    --check-frequency 5000
```
Renders the current collaterals every 5 seconds.

Screenshot 2025-04-10 at 5 12 28 PM

### CODE REVIEW

File: typescript/cli/src/rebalancer/rebalancer.ts [hunk 1]
```diff
@@ -1,11 +1,65 @@
...
+        name: ChainName;
+        collateral: number;
+        symbol: string;
+      }[] = [];
+
+      for (const token of collateralTokens) {
+        const adapter = token.getHypAdapter(multiProtocolProvider);
+        const bridgedSupply = await adapter.getBridgedSupply();
+        const collateral = token
+          .amount(bridgedSupply!)
```
Comment (fernandomg) [inline typescript/cli/src/rebalancer/rebalancer.ts:47]: the non-assertion is just to get going with the work, right?

**Review by fernandomg — APPROVED** [review]
🚀

File: typescript/cli/src/rebalancer/rebalancer.ts (hunk 1 above)
Comment (fzavalia) [reply typescript/cli/src/rebalancer/rebalancer.ts:47]: exactly
